"""
Django settings for project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    DEBUG=(bool, False),
    ALLOWED_HOSTS=(list, []),
    CORS_ALLOWED_ORIGINS=(list, []),
)
environ.Env.read_env(BASE_DIR / ".env")

SECRET_KEY = env("SECRET_KEY")

DEBUG = env("DEBUG")

ALLOWED_HOSTS = env("ALLOWED_HOSTS")

# UI version string, injected at deploy time (the backend image tag). Defaults to
# "dev" for local/unbuilt runs. Surfaced to users via the version API endpoint.
UI_VERSION = env("UI_VERSION", default="dev")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "whitenoise.runserver_nostatic",
    "django.contrib.staticfiles",
    "arango_api.apps.ArangoAPIConfig",
    "api",
    "rest_framework",
    "corsheaders",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

REACT_APP_BUILD_DIR = BASE_DIR / "react/build"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            REACT_APP_BUILD_DIR,
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Directories where Django's 'collectstatic' will look for additional static files
STATICFILES_DIRS = [
    REACT_APP_BUILD_DIR / "static",
]

# The absolute path to the directory where 'collectstatic' will collect static files for deployment.
STATIC_ROOT = BASE_DIR / "staticfiles_collected"

# CompressedManifestStaticFilesStorage handles compression and adds hashes to filenames for caching.
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# --- Whitenoise specific settings ---
WHITENOISE_ROOT = REACT_APP_BUILD_DIR

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS settings - use CORS_ALLOWED_ORIGINS in production
# Set CORS_ALLOW_ALL_ORIGINS=true in .env only for local development
CORS_ALLOW_ALL_ORIGINS = env.bool("CORS_ALLOW_ALL_ORIGINS", default=False)
CORS_ALLOWED_ORIGINS = env("CORS_ALLOWED_ORIGINS")

# HTTPS settings - enable these in production
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)

# ArangoDB settings
# Test configuration uses separate port (8530) and database names to avoid conflicts
# with development instance. Set ARANGO_TEST_MODE=true to use test configuration.
ARANGO_TEST_MODE = env.bool("ARANGO_TEST_MODE", default=False)

if ARANGO_TEST_MODE:
    # Test configuration - uses port 8530 and "-Test" suffix databases
    ARANGO_DB_HOST = env("ARANGO_TEST_HOST", default="http://127.0.0.1:8530")
    ARANGO_DB_USER = env("ARANGO_DB_USER", default="root")
    ARANGO_DB_PASSWORD = env("ARANGO_TEST_PASSWORD", default="test")
    ARANGO_DB_NAME_ONTOLOGIES = "Cell-KN-Ontologies-Test"
    ARANGO_DB_NAME_PHENOTYPES = "Cell-KN-Phenotypes-Test"
    GRAPH_NAME_ONTOLOGIES = "ontologies"
    GRAPH_NAME_PHENOTYPES = "phenotypes"
else:
    # Development/production configuration
    ARANGO_DB_HOST = env("ARANGO_DB_HOST")
    ARANGO_DB_USER = env("ARANGO_DB_USER")
    ARANGO_DB_PASSWORD = env("ARANGO_DB_PASSWORD")
    ARANGO_DB_NAME_ONTOLOGIES = env("ARANGO_DB_NAME_ONTOLOGIES")
    ARANGO_DB_NAME_PHENOTYPES = env("ARANGO_DB_NAME_PHENOTYPES")
    GRAPH_NAME_ONTOLOGIES = env("GRAPH_NAME_ONTOLOGIES")
    GRAPH_NAME_PHENOTYPES = env("GRAPH_NAME_PHENOTYPES")

# ArangoDB client hardening (see arango_api/db.py and arango_api/circuit_breaker.py).
# request_timeout bounds the connect+read time of every DB call so a slow query
# or a wedged DB fails fast instead of pinning a gunicorn thread until the worker
# timeout (default 30s) SIGKILLs it -- keep this comfortably under that timeout.
ARANGO_REQUEST_TIMEOUT = env.float("ARANGO_REQUEST_TIMEOUT", default=20.0)
# Low retry count so a down DB does not multiply each call by urllib3 connect
# retries; the circuit breaker handles "stop trying", not blind retries.
ARANGO_RETRY_ATTEMPTS = env.int("ARANGO_RETRY_ATTEMPTS", default=1)
# Trip the breaker after this many consecutive failures, then fail fast for
# reset_timeout seconds before letting a single trial request probe the DB.
ARANGO_CB_FAILURE_THRESHOLD = env.int("ARANGO_CB_FAILURE_THRESHOLD", default=5)
ARANGO_CB_RESET_TIMEOUT = env.float("ARANGO_CB_RESET_TIMEOUT", default=15.0)

# Logging configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "arango_api": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
    },
}
