/**
 * Constants barrel file - re-exports all constants
 */

// API endpoints
export {
  API_BASE,
  AQL_ENDPOINT,
  COLLECTION_DOCUMENT_ENDPOINT,
  COLLECTION_ENDPOINT,
  COLLECTIONS_ENDPOINT,
  CONNECTING_PATHS_ENDPOINT,
  DOCUMENT_DETAILS_ENDPOINT,
  EDGE_FILTER_OPTIONS_ENDPOINT,
  GRAPH_ENDPOINT,
  NEIGHBOR_COLLECTIONS_ENDPOINT,
  NODES_DETAILS_ENDPOINT,
  SEARCH_ENDPOINT,
  SHORTEST_PATHS_ENDPOINT,
  SUNBURST_ENDPOINT,
  WORKFLOW_PRESETS_ENDPOINT,
} from "./api";

// External URLs
export {
  DEFAULT_FTU_ILLUSTRATION_URL,
  FTU_ILLUSTRATIONS_API_URL,
  FTU_ILLUSTRATIONS_JSONLD_URL,
} from "./external";

// Graph configuration defaults
export {
  COLLAPSE_OPTIONS,
  DEFAULT_COLLAPSE_ON_START,
  DEFAULT_DEPTH,
  DEFAULT_EDGE_DIRECTION,
  DEFAULT_EDGE_FONT_SIZE,
  DEFAULT_FIND_SHORTEST_PATHS,
  DEFAULT_GRAPH_TYPE,
  DEFAULT_INCLUDE_INTER_NODE_EDGES,
  DEFAULT_LABEL_STATES,
  DEFAULT_NODE_FONT_SIZE,
  DEFAULT_NODE_LIMIT,
  DEFAULT_SET_OPERATION,
  DEFAULT_USE_FOCUS_NODES,
  DEPTH_OPTIONS,
  DIRECTION_OPTIONS,
  EXPANSION_DEPTH,
  GRAPH_STATUS,
  LAYOUT_MODE_OPTIONS,
  ORIGIN_FILTER_OPTIONS,
  PHENOTYPES_ENABLED,
  SET_OPERATION_OPTIONS,
} from "./graph";

// Workflow builder utilities (presets are fetched from the backend API)
export {
  createEmptyPhase,
  DEFAULT_PHASE_SETTINGS,
  QUERY_DEFAULTS,
  UI_DEFAULTS,
} from "./workflowPresets";
