import plotManifest from "assets/plot-manifest.json";
import { getDatasetFigures, getDatasetPlotKey } from "./datasetFigures";

const manifest = {
  tag: "v1.0.0-rc.10",
  datasets: {
    "skin_of_body/7d9c31": {
      dir: "skin_of_body/sc-nsforest-qc-nf/results/skin_of_body-Sole-Boldo-Commun Biol-2020-7d9c31",
      figures: {
        silhouette_fscore_summary: { html: "silhouette.html", svg: "silhouette.svg" },
        dendrogram: { svg: "dendrogram.svg" },
        stacked_violin: { svg: "violin.svg" },
      },
    },
    "retina/cbd4aa": {
      dir: "retina/sc-nsforest-qc-nf/results/retina-Li-Nat Genet-2026-cbd4aa",
      figures: {
        silhouette_fscore_summary: { svg: "silhouette.svg" },
        dendrogram: { svg: "d.svg" },
      },
    },
  },
};

const csd = { _id: "CSD/ba0fb2d9-28c9-4149-8591-694e0b7d9c31__skin_of_body" };

describe("getDatasetPlotKey", () => {
  it("takes the anatomical structure and the last six characters of the UUID", () => {
    expect(getDatasetPlotKey(csd)).toBe("skin_of_body/7d9c31");
  });

  it("ignores documents from other collections", () => {
    expect(getDatasetPlotKey({ _id: "CS/some-cell-set" })).toBeNull();
  });

  it("returns null rather than throwing on a malformed or absent document", () => {
    expect(getDatasetPlotKey(null)).toBeNull();
    expect(getDatasetPlotKey({})).toBeNull();
    expect(getDatasetPlotKey({ _id: "CSD/no-anatomy-suffix" })).toBeNull();
  });
});

describe("getDatasetFigures", () => {
  it("returns the three figures in display order", () => {
    expect(getDatasetFigures(csd, manifest).map((figure) => figure.key)).toEqual([
      "silhouette_fscore_summary",
      "dendrogram",
      "stacked_violin",
    ]);
  });

  it("percent-encodes the spaces in a published directory name", () => {
    const [silhouette] = getDatasetFigures(csd, manifest);
    expect(silhouette.src).toBe(
      "/plots/v1.0.0-rc.10/skin_of_body/sc-nsforest-qc-nf/results/skin_of_body-Sole-Boldo-Commun%20Biol-2020-7d9c31/silhouette.svg",
    );
    expect(silhouette.src).not.toContain(" ");
  });

  it("shows the SVG and offers the interactive page alongside it", () => {
    const [silhouette] = getDatasetFigures(csd, manifest);
    expect(silhouette.src).toMatch(/\.svg$/);
    expect(silhouette.interactiveUrl).toMatch(/\.html$/);
  });

  it("has no interactive page for a dataset that was published without one", () => {
    const [silhouette] = getDatasetFigures({ _id: "CSD/0000-0000-0000-cbd4aa__retina" }, manifest);
    expect(silhouette.src).toMatch(/\.svg$/);
    expect(silhouette.interactiveUrl).toBeNull();
  });

  it("omits a figure the dataset has no file for", () => {
    const keys = getDatasetFigures({ _id: "CSD/0000-0000-0000-cbd4aa__retina" }, manifest).map(
      (figure) => figure.key,
    );
    expect(keys).not.toContain("stacked_violin");
  });

  it("returns nothing for a dataset absent from the manifest", () => {
    expect(getDatasetFigures({ _id: "CSD/0000-0000-0000-abcdef__neocortex" }, manifest)).toEqual(
      [],
    );
    expect(getDatasetFigures({ _id: "CS/some-cell-set" }, manifest)).toEqual([]);
  });
});

// The manifest is generated by scripts/dev/build-plot-manifest.py and committed.
// These guard the shape the component depends on, so a bad regeneration fails
// here rather than as missing figures in the browser.
describe("the committed plot manifest", () => {
  it("names the nlm-ckn tag its paths are published under", () => {
    expect(plotManifest.tag).toMatch(/^v\d+\.\d+\.\d+/);
  });

  it("records at least one figure for every dataset it lists", () => {
    const entries = Object.entries(plotManifest.datasets);
    expect(entries.length).toBeGreaterThan(0);
    for (const [key, entry] of entries) {
      expect(key).toMatch(/^[^/]+\/[0-9a-f]{6}$/);
      expect(entry.dir).toContain("/results/");
      expect(Object.keys(entry.figures).length).toBeGreaterThan(0);
    }
  });

  it("resolves a real cell set dataset to figure URLs under the manifest tag", () => {
    const [firstKey] = Object.keys(plotManifest.datasets);
    const [anatomy, hash] = firstKey.split("/");
    const figures = getDatasetFigures({
      _id: `CSD/00000000-0000-0000-0000-0000${hash}__${anatomy}`,
    });
    expect(figures.length).toBeGreaterThan(0);
    for (const figure of figures) {
      expect(figure.src.startsWith(`/plots/${plotManifest.tag}/`)).toBe(true);
    }
  });
});
